export const CAR_INITIALIZE  = 'CAR_INITIALIZE';

export const CAR_OPTIONS_FETCH_REQUEST = 'CAR_OPTIONS_FETCH_REQUEST';
export const CAR_OPTIONS_FETCH_SUCCESS = 'CAR_OPTIONS_FETCH_SUCCESS';
export const CAR_OPTIONS_FETCH_FAILURE = 'CAR_OPTIONS_FETCH_FAILURE';

export const CAR_FETCH_REQUEST = 'CAR_FETCH_REQUEST';
export const CAR_FETCH_SUCCESS = 'CAR_FETCH_SUCCESS';
export const CAR_FETCH_FAILURE = 'CAR_FETCH_FAILURE';

export const CARS_FETCH_REQUEST = 'CARS_FETCH_REQUEST';
export const CARS_FETCH_SUCCESS = 'CARS_FETCH_SUCCESS';
export const CARS_FETCH_FAILURE = 'CARS_FETCH_FAILURE';

export const CAR_CREATE_REQUEST  = 'CAR_CREATE_REQUEST';
export const CAR_CREATE_SUCCESS  = 'CAR_CREATE_SUCCESS';
export const CAR_CREATE_FAILURE  = 'CAR_CREATE_FAILURE';

export const CAR_UPDATE_REQUEST  = 'CAR_UPDATE_REQUEST';
export const CAR_UPDATE_SUCCESS  = 'CAR_UPDATE_SUCCESS';
export const CAR_UPDATE_FAILURE  = 'CAR_UPDATE_FAILURE';
