export const LOGIN_REQUEST 	     = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS 			 = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE 			 = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST      = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS      = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE      = 'LOGOUT_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const CARS_REQUEST        = 'CARS_REQUEST';
export const CARS_SUCCESS        = 'CARS_SUCCESS';
export const CARS_FAILURE        = 'CARS_FAILURE';

export const CAR_REQUEST         = 'CAR_REQUEST';
export const CAR_SUCCESS         = 'CAR_SUCCESS';
export const CAR_FAILURE         = 'CAR_FAILURE';

export const CAR_CREATE_REQUEST  = 'CAR_CREATE_REQUEST';
export const CAR_CREATE_SUCCESS  = 'CAR_CREATE_SUCCESS';
export const CAR_CREATE_FAILURE  = 'CAR_CREATE_FAILURE';

export const CAR_UPDATE_REQUEST  = 'CAR_UPDATE_REQUEST';
export const CAR_UPDATE_SUCCESS  = 'CAR_UPDATE_SUCCESS';
export const CAR_UPDATE_FAILURE  = 'CAR_UPDATE_FAILURE';

export const CARS_OPTIONS_REQUEST = 'CARS_OPTIONS_REQUEST';
export const CARS_OPTIONS_SUCCESS = 'CARS_OPTIONS_SUCCESS';
export const CARS_OPTIONS_FAILURE = 'CARS_OPTIONS_FAILURE';

export const USERS_REQUEST       = 'USERS_REQUEST';
export const USERS_SUCCESS       = 'USERS_SUCCESS';
export const USERS_FAILURE       = 'USERS_FAILURE';

export const USER_REQUEST        = 'USER_REQUEST';
export const USER_SUCCESS        = 'USER_SUCCESS';
export const USER_FAILURE        = 'USER_FAILURE';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

export const RIDES_REQUEST       = 'RIDES_REQUEST';
export const RIDES_SUCCESS       = 'RIDES_SUCCESS';
export const RIDES_FAILURE       = 'RIDES_FAILURE';

export const RIDE_REQUEST        = 'RIDE_REQUEST';
export const RIDE_SUCCESS        = 'RIDE_SUCCESS';
export const RIDE_FAILURE        = 'RIDE_FAILURE';

export const RIDE_CREATE_REQUEST = 'RIDE_CREATE_REQUEST';
export const RIDE_CREATE_SUCCESS = 'RIDE_CREATE_SUCCESS';
export const RIDE_CREATE_FAILURE = 'RIDE_CREATE_FAILURE';

export const RIDE_UPDATE_REQUEST = 'RIDE_UPDATE_REQUEST';
export const RIDE_UPDATE_SUCCESS = 'RIDE_UPDATE_SUCCESS';
export const RIDE_UPDATE_FAILURE = 'RIDE_UPDATE_FAILURE';

export const RIDE_OPTIONS_REQUEST = 'RIDE_OPTIONS_REQUEST';
export const RIDE_OPTIONS_SUCCESS = 'RIDE_OPTIONS_SUCCESS';
export const RIDE_OPTIONS_FAILURE = 'RIDE_OPTIONS_FAILURE';

export const RIDES_DRIVER_REQUEST = 'RIDES_DRIVER_REQUEST';
export const RIDES_DRIVER_SUCCESS = 'RIDES_DRIVER_SUCCESS';
export const RIDES_DRIVER_FAILURE = 'RIDES_DRIVER_FAILURE';

export const RIDES_PASSENGER_REQUEST = 'RIDES_PASSENGER_REQUEST';
export const RIDES_PASSENGER_SUCCESS = 'RIDES_PASSENGER_SUCCESS';
export const RIDES_PASSENGER_FAILURE = 'RIDES_PASSENGER_FAILURE';

export const RIDE_REQUEST_CREATE_REQUEST = 'RIDE_REQUEST_CREATE_REQUEST';
export const RIDE_REQUEST_CREATE_SUCCESS = 'RIDE_REQUEST_CREATE_SUCCESS';
export const RIDE_REQUEST_CREATE_FAILURE = 'RIDE_REQUEST_CREATE_FAILURE';

export const LOGIN_FROM_COOKIE_SUCCESS = 'LOGIN_FROM_COOKIE_SUCCESS';
