export const car = {
  id: 1,
  brand: 'Ford',
  model: 'Focus',
  full_name: 'Ford Focus',
  production_year: '1999',
  comfort: 'basic',
  comfort_stars: 1,
  places: 3,
  places_full: '3 places',
  color: 'black',
  category: 'sedan',
  created_at: '2016-05-06T20:33:13.861Z',
  owner_id: 1,
  car_photo: 'http://example.com/car_photo.jpg',
}
