export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';

export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';

export const CURRENT_USER_FETCH_REQUEST = 'CURRENT_USER_FETCH_REQUEST';
export const CURRENT_USER_FETCH_SUCCESS = 'CURRENT_USER_FETCH_SUCCESS';
export const CURRENT_USER_FETCH_FAILURE = 'CURRENT_USER_FETCH_FAILURE';

export const CURRENT_USER_CREATE_REQUEST = 'CURRENT_USER_CREATE_REQUEST';
export const CURRENT_USER_CREATE_SUCCESS = 'CURRENT_USER_CREATE_SUCCESS';
export const CURRENT_USER_CREATE_FAILURE = 'CURRENT_USER_CREATE_FAILURE';

export const CURRENT_USER_UPDATE_REQUEST = 'CURRENT_USER_UPDATE_REQUEST';
export const CURRENT_USER_UPDATE_SUCCESS = 'CURRENT_USER_UPDATE_SUCCESS';
export const CURRENT_USER_UPDATE_FAILURE = 'CURRENT_USER_UPDATE_FAILURE';
