export const RIDE_OPTIONS_FETCH_REQUEST = 'RIDE_OPTIONS_FETCH_REQUEST';
export const RIDE_OPTIONS_FETCH_SUCCESS = 'RIDE_OPTIONS_FETCH_SUCCESS';
export const RIDE_OPTIONS_FETCH_FAILURE = 'RIDE_OPTIONS_FETCH_FAILURE';

export const RIDE_FETCH_REQUEST = 'RIDE_FETCH_REQUEST';
export const RIDE_FETCH_SUCCESS = 'RIDE_FETCH_SUCCESS';
export const RIDE_FETCH_FAILURE = 'RIDE_FETCH_FAILURE';

export const RIDES_FETCH_REQUEST = 'RIDES_FETCH_REQUEST';
export const RIDES_FETCH_SUCCESS = 'RIDES_FETCH_SUCCESS';
export const RIDES_FETCH_FAILURE = 'RIDES_FETCH_FAILURE';

export const RIDE_CREATE_REQUEST = 'RIDE_CREATE_REQUEST';
export const RIDE_CREATE_SUCCESS = 'RIDE_CREATE_SUCCESS';
export const RIDE_CREATE_FAILURE = 'RIDE_CREATE_FAILURE';

export const RIDE_UPDATE_REQUEST = 'RIDE_UPDATE_REQUEST';
export const RIDE_UPDATE_SUCCESS = 'RIDE_UPDATE_SUCCESS';
export const RIDE_UPDATE_FAILURE = 'RIDE_UPDATE_FAILURE';

export const RIDES_DRIVER_FETCH_REQUEST = 'RIDES_DRIVER_FETCH_REQUEST';
export const RIDES_DRIVER_FETCH_SUCCESS = 'RIDES_DRIVER_FETCH_SUCCESS';
export const RIDES_DRIVER_FETCH_FAILURE = 'RIDES_DRIVER_FETCH_FAILURE';

export const RIDES_PASSENGER_FETCH_REQUEST = 'RIDES_PASSENGER_FETCH_REQUEST';
export const RIDES_PASSENGER_FETCH_SUCCESS = 'RIDES_PASSENGER_FETCH_SUCCESS';
export const RIDES_PASSENGER_FETCH_FAILURE = 'RIDES_PASSENGER_FETCH_FAILURE';

export const RIDE_REQUEST_CREATE_REQUEST = 'RIDE_REQUEST_CREATE_REQUEST';
export const RIDE_REQUEST_CREATE_SUCCESS = 'RIDE_REQUEST_CREATE_SUCCESS';
export const RIDE_REQUEST_CREATE_FAILURE = 'RIDE_REQUEST_CREATE_FAILURE';

export const RIDE_REQUEST_CHANGE_REQUEST = 'RIDE_REQUEST_CHANGE_REQUEST'
export const RIDE_REQUEST_CHANGE_SUCCESS = 'RIDE_REQUEST_CHANGE_SUCCESS'
export const RIDE_REQUEST_CHANGE_FAILURE = 'RIDE_REQUEST_CHANGE_FAILURE'

export const RIDES_SEARCH_FORM = 'RIDES_SEARCH_FORM'
