export { default as Application }      from '../containers/Application'
export { default as HeaderNew }        from './HeaderNew'
export { default as Home }             from './Home'
export { default as LoginPage }        from '../containers/session/LoginPage'

export { default as UsersNewPage }     from '../containers/users/UsersNewPage'
export { default as UsersIndexPage }   from '../containers/users/UsersIndexPage'
export { default as UsersShowPage }    from '../containers/users/UsersShowPage'
export { default as UsersEditPage }    from '../containers/users/UsersEditPage'

export { default as CarsNewPage }      from '../containers/cars/CarsNewPage'
export { default as CarsIndexPage }    from '../containers/cars/CarsIndexPage'
export { default as CarsShowPage }     from '../containers/cars/CarsShowPage'
export { default as CarsEditPage }     from '../containers/cars/CarsEditPage'

export { default as RidesNewPage }     from '../containers/rides/RidesNewPage'
export { default as RidesIndexPage }   from '../containers/rides/RidesIndexPage'
export { default as RidesDriverIndexPage }    from '../containers/rides/RidesDriverIndexPage'
export { default as RidesPassengerIndexPage } from '../containers/rides/RidesPassengerIndexPage'
export { default as RidesShowPage }    from '../containers/rides/RidesShowPage'
export { default as RidesEditPage }    from '../containers/rides/RidesEditPage'
